# Generated by Django 5.1.7 on 2025-04-02 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('chain', models.CharField(db_index=True, max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('usd_price', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('usd_price_24h_percent_change', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('usd_price_24h_usd_change', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('address', 'chain')},
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('chain', models.CharField(max_length=50)),
                ('balance_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('address', 'chain')},
            },
        ),
        migrations.CreateModel(
            name='WalletToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=50)),
                ('token_balance_formatted', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('usd_value', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('usd_value_24h_usd_change', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'token', 'chain')},
            },
        ),
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.wallet')),
            ],
            options={
                'unique_together': {('user', 'wallet')},
            },
        ),
    ]
